lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # la clave privada
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # la clave pública
    pass_phrase:      'TU_CONTRASEÑA_SECRETA' # la contraseña utilizada al generar la clave privada
    token_ttl:        3600

